version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Install Julia
      - curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.5-linux-x86_64.tar.gz | tar -xz
      # Prepare the docs environment (chain commands to preserve environment)
      - export PATH="$PWD/julia-1.10.5/bin:$PATH" && export HYQMOM_SKIP_PLOTTING="true" && export JULIA_NUM_THREADS="2" && julia --project=docs -e "using Pkg; Pkg.develop(PackageSpec(path=\".\")); Pkg.instantiate()"
    post_build:
      # Build Documenter docs (chain commands to preserve environment)
      - export PATH="$PWD/julia-1.10.5/bin:$PATH" && export HYQMOM_SKIP_PLOTTING="true" && export JULIA_NUM_THREADS="2" && julia --project=docs docs/make.jl
  # Prevent automatic Sphinx/MkDocs build by using explicit commands
  commands: []

# No additional formats needed - Documenter.jl builds HTML directly
# formats: [] can be added if you want downloadable versions (htmlzip, pdf, epub)
