version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Install Julia (adjust version as needed)
      - curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.5-linux-x86_64.tar.gz | tar -xz
      - export PATH="$PWD/julia-1.10.5/bin:$PATH"
      # Prepare the docs environment and develop the package
      - julia --project=HyQMOM.jl/docs -e 'using Pkg; Pkg.develop(PackageSpec(path="HyQMOM.jl")); Pkg.instantiate()'
    build:
      # Build Documenter docs; HTML must go into $READTHEDOCS_OUTPUT/html
      - export PATH="$PWD/julia-1.10.5/bin:$PATH"
      - julia --project=HyQMOM.jl/docs HyQMOM.jl/docs/make.jl
  environment:
    # Avoid heavy plotting deps during docs build
    HYQMOM_SKIP_PLOTTING: "true"
    JULIA_NUM_THREADS: "2"

# Tell RTD where the docs are built (dummy sphinx config to satisfy RTD)
sphinx:
  configuration: docs/conf.py
