name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.9', '1.10', '1.11']
        include:
          - julia-version: '1.11'
            experimental: true  # Allow Julia 1.11 to fail while ecosystem stabilizes
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    
    - name: Install MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y mpich libmpich-dev
    
    - name: Cache Julia packages
      uses: actions/cache@v3
      with:
        path: ~/.julia
        key: ${{ runner.os }}-julia-${{ matrix.julia-version }}-${{ hashFiles('**/Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-${{ matrix.julia-version }}-
    
    - name: Install dependencies
      run: |
        if [ "${{ matrix.julia-version }}" == "1.9" ]; then
          # Julia 1.9: Disable auto-precompilation to avoid Test extension bug
          julia --project=. -e '
            ENV["JULIA_PKG_PRECOMPILE_AUTO"] = "0"
            using Pkg
            Pkg.instantiate()
            Pkg.build("MPI")
          '
        else
          # Julia 1.10+: Standard instantiation
          julia --project=. -e '
            using Pkg
            Pkg.instantiate()
            Pkg.build("MPI")
          '
        fi
      env:
        PYTHON: ""  # Tell PyCall to skip Python - not needed for tests
        HYQMOM_SKIP_PLOTTING: true
    
    - name: Run unit tests
      run: |
        if [ "${{ matrix.julia-version }}" == "1.9" ]; then
          # Julia 1.9: Use workaround for Test extension bug
          TEST_GOLDEN_SIMULATION=false CI=true julia --project=. --color=yes test/ci_test.jl
        else
          # Julia 1.10+: Standard testing
          TEST_GOLDEN_SIMULATION=false CI=true julia --project=. --color=yes -e 'using Pkg; Pkg.test()'
        fi
      env:
        CI: true
        PYTHON: ""  # Skip PyCall/PyPlot for all versions
        HYQMOM_SKIP_PLOTTING: true
    
    - name: Run MPI golden file tests
      run: |
        ./test/test_mpi_goldenfiles.sh
    
    - name: Run MPI integration tests
      run: |
        ./test/run_mpi_tests.sh