name: CI
on:
  push:
    branches:
      - main
      - master
      - julia3
  pull_request:
    branches:
      - main
      - master
      - julia3

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.9'
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    
    env:
      # Skip visualization packages in CI (no display available)
      HYQMOM_SKIP_PLOTTING: "true"
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      
      - uses: julia-actions/cache@v1
      
      # Remove GLMakie from Project.toml for CI (headless environment)
      - name: Remove GLMakie dependency for CI
        run: |
          julia --project=. -e 'using Pkg; Pkg.rm("GLMakie"; mode=PKGMODE_PROJECT)'
      
      - uses: julia-actions/julia-buildpkg@v1
      
      - uses: julia-actions/julia-runtest@v1
      
      - uses: julia-actions/julia-processcoverage@v1
      
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
