name: CI
on:
  push:
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.9'
          - '1.10'
          - '1.11'
        os:
          - ubuntu-latest
        arch:
          - x64
    
    env:
      # Skip visualization packages in CI (no display available)
      HYQMOM_SKIP_PLOTTING: "true"
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v2

      # Remove GLMakie from Project.toml for CI (headless environment)
      - name: Remove GLMakie dependency for CI
        env:
          HYQMOM_SKIP_PLOTTING: "true"
        run: |
          echo "Removing GLMakie to avoid X11/GLFW errors in CI..."
          # Remove GLMakie from Project.toml in multiple sections
          if grep -q "GLMakie" Project.toml; then
            echo "Found GLMakie in Project.toml, removing from all sections..."
            # Remove from [deps]
            sed -i '/^GLMakie = /d' Project.toml
            # Remove from [compat]
            sed -i '/^GLMakie = /d' Project.toml
            # Remove GLMakie from [targets] test array
            sed -i 's/, "GLMakie"//g' Project.toml
            sed -i 's/"GLMakie", //g' Project.toml
            sed -i 's/"GLMakie"//g' Project.toml
            echo "GLMakie removed from Project.toml"
            echo "Modified Project.toml:"
            cat Project.toml
          else
            echo "GLMakie not found in Project.toml"
          fi
          # Remove Manifest to force clean resolve
          if [ -f Manifest.toml ]; then
            rm -f Manifest.toml
            echo "Manifest.toml removed for clean resolve"
          fi
      
      - uses: julia-actions/julia-buildpkg@v1
      
      - uses: julia-actions/julia-runtest@v1
      
      - uses: julia-actions/julia-processcoverage@v1
      
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
