function cfg = create_config(Np, tmax, Kn, Ma, flag2D)
% create_config Create configuration struct with simulation parameters
%
% Inputs:
%   Np - number of grid points
%   tmax - maximum simulation time
%   Kn - Knudsen number
%   Ma - Mach number  
%   flag2D - 2D simulation flag
%
% Output:
%   cfg - configuration struct with all simulation parameters

cfg = struct( ...
    'Np', Np, ...
    'CFL', 0.5, ...
    'xmin', -0.5, 'xmax', 0.5, ...
    'ymin', -0.5, 'ymax', 0.5, ...
    'tmax', tmax, ...
    'nnmax', 20000000, ...      % maximum number of time steps
    'dtmax', Kn, ...            % largest dt to resolve collisions
    'Kn', Kn, 'Ma', Ma, 'flag2D', flag2D, ...
    'N', 4, 'Nmom', 35, 'Nmom5', 21, ...
    'rhol', 1, 'rhor', 0.01, ...
    'U0', 0, 'V0', 0, 'W0', 0, ...
    'T', 1, ...
    'r110', 0.0, 'r101', 0.0, 'r011', 0.0, ...
    's3max', 4.0 + abs(Ma)/2.0, ...
    'h2min', 1e-8, ...
    'itrealmax', 6, ...
    'Csize', floor(0.1 * Np) ...
);

end
